In [1]:
# Deep learning related imports
import torch
from utils.data_loading import *
from utils.visualizations import * 
from utils.constants import * 

In [2]:
PPI_NUM_INPUT_FEATURES = 50
PPI_NUM_CLASSES = 121

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")  # checking whether you have a GPU

config = {
    'dataset_name': DatasetType.PPI.name,
    'num_of_epochs': 200,
    'patience_period': 100,
    
    'should_visualize': False,
    'batch_size': 1,
    'force_cpu': False,
    'should_test': True,
    'console_log_freq': 10,
    'checkpoint_freq': 5,
    'enable_tensorboard': True,
    'weight_decay': 0,
    'ppi_load_test_only': False,
    
    'lr': 5e-3,
    'num_of_layers': 3,  # PPI has got 42% of nodes with all 0 features - that's why 3 layers are useful
    'num_heads_per_layer': [4, 4, 6],  # other values may give even better results from the reported ones
    'num_features_per_layer': [PPI_NUM_INPUT_FEATURES, 256, 256, PPI_NUM_CLASSES],  # 64 would also give ~0.975 uF1!
    'add_skip_connection': True,  # skip connection is very important! (keep it otherwise micro-F1 is almost 0)
    'bias': True,  # bias doesn't matter that much
    'dropout': 0.0,  # dropout hurts the performance (best to keep it at 0)
    'layer_type': LayerType.IMP3,  # the only implementation that supports the inductive setting
    
    'neighbourhood_degree': 2,
    'adjacency_mode': AdjacencyMode.OneStep
}

print("Cuda is available:", torch.cuda.is_available())

data_loader_train, data_loader_val, data_loader_test = load_graph_data(config, device)
# Let's fetch a single batch from the train graph data loader
node_features, node_labels, edge_index = next(iter(data_loader_train))

print('*' * 20)
print(node_features.shape, node_features.dtype)
print(node_labels.shape, node_labels.dtype)
print(edge_index.shape, edge_index.dtype)


Cuda is available: True
Start
torch.Size([1767, 1767])
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])
Elapsed Time: 0.054819345474243164
Loading train graph 1 to CPU. It has 1767 nodes and 744799 edges.
Start
torch.Size([1377, 1377])
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 1., 0., 0.],
        [0., 1., 1.,  ..., 1., 0., 0.],
        ...,
        [0., 1., 1.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])
Elapsed Time: 0.02888965606689453
Loading train graph 2 to CPU. It has 1377 nodes and 633091 edges.
Start
torch.Size([2263, 2263])
tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 1.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
 

KeyboardInterrupt: 

In [ ]:
#num_of_nodes = len(node_labels)
#plot_in_out_degree_distributions(edge_index, num_of_nodes, config['dataset_name'])

In [ ]:
from Scripts.script_PPI import * 

train_gat_ppi(config)

KeyboardInterrupt: 