In [30]:
from utils.experimentor import *
from utils.constants import *
import torch


In [31]:
config = {
    "dataset_name": Dataset.OGBN_ARXIV,
    "model_type": ModelType.GATV1,
    'num_of_epochs': 2,
    'num_of_runs': 1,
    'patience_period': 1,
    
    #'should_visualize': False,
    'batch_size': 20000,
    'test_batch_size': 20000,
    'num_workers': 0,
    'force_cpu': False,
    'test_frequency': 5,
    'console_log_freq': 1,
    'do_train_tqdm_logging': True,
    
    'lr': 0.01,
    'num_of_layers': 2,  # PPI has got 42% of nodes with all 0 features - that's why 3 layers are useful
    'num_heads': 1,
    'hidden_size': 64,
    'dropout': 0.5,  
    "use_layer_norm": True,
    
    #'neighbourhood_degree': 2,
    #'adjacency_mode': AdjacencyMode.OneStep
}

In [35]:
from torch_geometric.utils import to_dense_adj

edge_index = torch.tensor([[0,0,1,1,2,2],[1,2,3,4,4,5]], dtype=torch.long)  # 2 x E
x = torch.tensor([[1], [1], [1], [1], [1], [1]], dtype=torch.float)  # N x emb(in)
print(edge_index)


def edge_index_times_x(edge_index, x):
    adj = to_dense_adj(edge_index)[0]
    adj = torch.linalg.matrix_power(adj, x)
    edge_index = (adj > 0).nonzero().t()
    edge_weight = 1/x * torch.ones(edge_index.size(1))
          
    return edge_index, edge_weight
    
hop2, w2 = edge_index_times_x(edge_index, 2)
hop3, w3 = edge_index_times_x(edge_index, 3)
print(hop2)
print(w2)
print(hop3)
print(w3) # correctly working

tensor([[0, 0, 1, 1, 2, 2],
        [1, 2, 3, 4, 4, 5]])
tensor([[0, 0, 0],
        [3, 4, 5]])
tensor([0.5000, 0.5000, 0.5000])
tensor([], size=(2, 0), dtype=torch.int64)
tensor([])


In [33]:
##experimentor = Experimentor(config)
#experimentor.run()