In [1]:
import torch
from utils.experimentorUtils import getExperimentor
from utils.constants import *

In [2]:
config = {
    "dataset_name": Dataset.CORA,
    "model_type": ModelType.GATV2,
    'num_of_epochs': 500,
    'num_of_runs': 1,
    'patience_period': 100,
    
    'batch_size': 256,
    'test_batch_size': 256,
    'num_workers': 2,
    'force_cpu': True,
    'test_frequency': 5,
    'console_log_freq': 1,
    'do_train_tqdm_logging': False,
    
    'lr': 0.001,
    'num_of_layers': 3, 
    'num_heads': 1,
    'hidden_size': 128,
    'dropout': 0.5,  
    "use_layer_norm": False,
    "use_batch_norm": False,
    
    'nbor_degree': 1,
    'adj_mode': AdjacencyMode.OneStep,
    'sparse': True
}

In [3]:
experimentor = getExperimentor(config["dataset_name"])(config)
experimentor.run_wrapper()

Run 01:


Epoch 01:   0%|          | 0/2708 [00:00<?, ?it/s]

max tensor(2395) tensor(1979)
shape torch.Size([10895]) torch.Size([10895])
tensor([   0,    0,    0,  ..., 2393, 2394, 2395])
tensor([   0,  256,  257,  ..., 1979, 1979, 1979])
max tensor(1979) tensor(867)
shape torch.Size([5816]) torch.Size([5816])
tensor([   0,    0,    0,  ..., 1977, 1978, 1979])
tensor([  0, 256, 257,  ..., 867, 867, 867])
max tensor(867) tensor(255)
shape torch.Size([1132]) torch.Size([1132])
tensor([  0,   1,   2,  ..., 865, 866, 867])
tensor([  0,   1,   2,  ..., 253, 254, 255])


Epoch 01:   9%|▉         | 256/2708 [00:02<00:23, 104.76it/s]

max tensor(2432) tensor(2073)
shape torch.Size([11227]) torch.Size([11227])
tensor([   0,    0,    0,  ..., 2430, 2431, 2432])
tensor([   0,  256,  257,  ..., 2038, 2056, 2057])
max tensor(2073) tensor(1002)
shape torch.Size([6339]) torch.Size([6339])
tensor([   0,    0,    0,  ..., 2072, 2073, 2073])
tensor([  0, 256, 257,  ..., 996, 998, 999])
max tensor(1002) tensor(255)
shape torch.Size([1304]) torch.Size([1304])
tensor([   0,    1,    2,  ..., 1000, 1001, 1002])
tensor([  0,   1,   2,  ..., 254, 254, 255])


Epoch 01:  19%|█▉        | 512/2708 [00:02<00:09, 226.01it/s]

max tensor(2427) tensor(2086)
shape torch.Size([11368]) torch.Size([11368])
tensor([   0,    0,    1,  ..., 2425, 2426, 2427])
tensor([   0,  256,    1,  ..., 2077, 2078, 2081])
max tensor(2086) tensor(953)
shape torch.Size([6353]) torch.Size([6353])
tensor([   0,    0,    1,  ..., 2084, 2085, 2086])
tensor([  0, 256,   1,  ..., 949, 950, 951])
max tensor(953) tensor(255)
shape torch.Size([1311]) torch.Size([1311])
tensor([  0,   1,   1,  ..., 951, 952, 953])
tensor([  0,   1, 238,  ..., 254, 255, 255])


Epoch 01:  38%|███▊      | 1024/2708 [00:03<00:03, 502.53it/s]

max tensor(2445) tensor(2065)
shape torch.Size([11164]) torch.Size([11164])
tensor([   0,    0,    0,  ..., 2443, 2444, 2445])
tensor([   0,  256,  257,  ..., 2047, 2059, 2064])
max tensor(2065) tensor(963)
shape torch.Size([6071]) torch.Size([6071])
tensor([   0,    0,    0,  ..., 2063, 2064, 2065])
tensor([  0, 256, 257,  ..., 961, 961, 961])
max tensor(963) tensor(255)
shape torch.Size([1185]) torch.Size([1185])
tensor([  0,   1,   2,  ..., 961, 962, 963])
tensor([  0,   1,   2,  ..., 252, 253, 255])
max 

Epoch 01:  47%|████▋     | 1280/2708 [00:03<00:02, 637.69it/s]

tensor(2457) tensor(2058)
shape torch.Size([11281]) torch.Size([11281])
tensor([   0,    0,    0,  ..., 2455, 2456, 2457])
tensor([   0,  150,  256,  ..., 2040, 2052, 2056])
max tensor(2058) tensor(1002)
shape torch.Size([6332]) torch.Size([6332])
tensor([   0,    0,    0,  ..., 2056, 2057, 2058])
tensor([  0, 150, 256,  ..., 988, 989, 993])
max tensor(1002) tensor(255)
shape torch.Size([1309]) torch.Size([1309])
tensor([   0,    0,    1,  ..., 1000, 1001, 1002])
tensor([  0, 150,   1,  ..., 252, 253, 254])


Epoch 01:  57%|█████▋    | 1536/2708 [00:03<00:01, 779.54it/s]

max tensor(2446) tensor(2037)
shape torch.Size([11148]) torch.Size([11148])
tensor([   0,    0,    1,  ..., 2444, 2445, 2446])
tensor([   0,  256,    1,  ..., 2030, 2032, 2035])
max tensor(2037) tensor(911)
shape torch.Size([5968]) torch.Size([5968])
tensor([   0,    0,    1,  ..., 2035, 2036, 2037])
tensor([  0, 256,   1,  ..., 897, 898, 898])
max tensor(911) tensor(255)
shape torch.Size([1208]) torch.Size([1208])
tensor([  0,   1,   1,  ..., 909, 910, 911])
tensor([  0,   1, 235,  ..., 253, 253, 255])
max 

Epoch 01:  66%|██████▌   | 1792/2708 [00:03<00:01, 908.31it/s]

tensor(2396) tensor(1978)
shape torch.Size([10851]) torch.Size([10851])
tensor([   0,    0,    1,  ..., 2394, 2395, 2396])
tensor([   0,  256,    1,  ..., 1956, 1959, 1976])
max tensor(1978) tensor(910)
shape torch.Size([5924]) torch.Size([5924])
tensor([   0,    0,    1,  ..., 1976, 1977, 1978])
tensor([  0, 256,   1,  ..., 909, 910, 910])
max tensor(910) tensor(255)
shape torch.Size([1224]) torch.Size([1224])
tensor([  0,   1,   2,  ..., 908, 909, 910])
tensor([  0,   1,   2,  ..., 254, 254, 255])
max 

Epoch 01:  76%|███████▌  | 2048/2708 [00:03<00:00, 1000.80it/s]

tensor(2435) tensor(2042)
shape torch.Size([11143]) torch.Size([11143])
tensor([   0,    0,    1,  ..., 2433, 2434, 2435])
tensor([   0,  256,    1,  ..., 2038, 2038, 2040])
max tensor(2042) tensor(939)
shape torch.Size([6122]) torch.Size([6122])
tensor([   0,    0,    1,  ..., 2040, 2041, 2042])
tensor([  0, 256,   1,  ..., 934, 935, 937])
max tensor(939) tensor(255)
shape torch.Size([1204]) torch.Size([1204])
tensor([  0,   1,   2,  ..., 937, 938, 939])
tensor([  0,   1,   2,  ..., 253, 254, 255])
max 

Epoch 01:  85%|████████▌ | 2304/2708 [00:04<00:00, 1060.09it/s]

tensor(2424) tensor(2065)
shape torch.Size([11264]) torch.Size([11264])
tensor([   0,    0,    0,  ..., 2422, 2423, 2424])
tensor([   0,  256,  257,  ..., 2055, 2057, 2058])
max tensor(2065) tensor(999)
shape torch.Size([6461]) torch.Size([6461])
tensor([   0,    0,    0,  ..., 2064, 2064, 2065])
tensor([  0, 256, 257,  ..., 997, 998, 998])
max tensor(999) tensor(255)
shape torch.Size([1313]) torch.Size([1313])
tensor([  0,   1,   2,  ..., 997, 998, 999])
tensor([  0,   1,   2,  ..., 254, 254, 255])


Epoch 01:  95%|█████████▍| 2560/2708 [00:04<00:00, 1161.81it/s]

max tensor(2423) tensor(2061)
shape torch.Size([11197]) torch.Size([11197])
tensor([   0,    0,    0,  ..., 2421, 2422, 2423])
tensor([   0,   10,   44,  ..., 2044, 2045, 2054])
max tensor(2061) tensor(1038)
shape torch.Size([6582]) torch.Size([6582])
tensor([   0,    0,    0,  ..., 2059, 2060, 2061])
tensor([   0,   10,   44,  ..., 1038, 1038, 1038])
max tensor(1038) tensor(255)
shape torch.Size([1373]) torch.Size([1373])
tensor([   0,    0,    0,  ..., 1036, 1037, 1038])
tensor([  0,  10,  44,  ..., 252, 253, 254])
max tensor(2250) tensor(1681)
shape torch.Size([9689]) torch.Size([9689])
tensor([   0,    0,    0,  ..., 2248, 2249, 2250])
tensor([   0,  148,  149,  ..., 1675, 1678, 1679])


Epoch 01: 100%|██████████| 2708/2708 [00:04<00:00, 1102.68it/s]

max tensor(1681) tensor(590)
shape torch.Size([4220]) torch.Size([4220])
tensor([   0,    0,    0,  ..., 1680, 1681, 1681])
tensor([  0, 148, 149,  ..., 589, 589, 590])
max tensor(590) tensor(147)
shape torch.Size([701]) torch.Size([701])
tensor([  0,   1,   2,   3,   4,   5,   6,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  23,  24,  24,
         25,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  34,  35,  36,
         36,  37,  38,  39,  40,  40,  41,  42,  43,  43,  44,  45,  46,  47,
         47,  47,  48,  49,  50,  51,  51,  52,  52,  52,  53,  54,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  67,  67,
         68,  69,  70,  71,  72,  73,  73,  74,  74,  75,  75,  76,  77,  78,
         79,  80,  80,  81,  82,  83,  84,  84,  85,  86,  86,  87,  87,  88,
         89,  90,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 1

Epoch 01: 100%|██████████| 2708/2708 [00:04<00:00, 558.40it/s] 


Epoch 01| Loss: 1.7785| Acc: 0.3165| Train Time: 4.8546s
max tensor(2431) tensor(2064)
shape torch.Size([11270]) torch.Size([11270])
tensor([   0,    0,    1,  ..., 2429, 2430, 2431])
tensor([   0,  256,    1,  ..., 2055, 2055, 2059])
max tensor(2064) tensor(1000)
shape torch.Size([6472]) torch.Size([6472])
tensor([   0,    0,    1,  ..., 2063, 2064, 2064])
tensor([  0, 256,   1,  ..., 998, 997, 998])
max tensor(1000) tensor(255)
shape torch.Size([1322]) torch.Size([1322])
tensor([   0,    1,    2,  ...,  998,  999, 1000])
tensor([  0,   1,   2,  ..., 252, 252, 253])
max tensor(2410) tensor(1990)
shape torch.Size([10933]) torch.Size([10933])
tensor([   0,    0,    1,  ..., 2408, 2409, 2410])
tensor([   0,  256,    1,  ..., 1982, 1983, 1986])
max tensor(1990) tensor(912)
shape torch.Size([5930]) torch.Size([5930])
tensor([   0,    0,    1,  ..., 1988, 1989, 1990])
tensor([  0, 256,   1,  ..., 912, 910, 910])
max tensor(912) tensor(255)
shape torch.Size([1190]) torch.Size([1190])
tensor(